[package]
name = "crossbeam_scope"
version = "0.1.0"
authors = ["Scott Carrion <scott.carrion@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.0"
