[package]
name = "mapped_stack_join"
version = "0.1.0"
authors = ["skeet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
